server:
  port: 8081
  max-http-header-size: 16KB
  tomcat:
    max-http-post-size: 16KB
    max-http-form-post-size: 16KB

spring:
  application:
    name: nutrilife-auth
  datasource:
    url: jdbc:postgresql://localhost:5432/nutrilife_auth
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000 # 24 hours in milliseconds
  refresh-expiration: 604800000 # 7 days in milliseconds

# Swagger/OpenAPI konfigürasyonu
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs

logging:
  level:
    com.superapp.nutrilife.auth: DEBUG
    org.springframework.security: DEBUG
