server:
  port: 8082
  max-http-header-size: 16KB
  tomcat:
    max-http-post-size: 16KB
    max-http-form-post-size: 16KB

spring:
  application:
    name: nutrilife-profile-service
  
  datasource:
    url: jdbc:postgresql://postgres:5432/nutrilife_profile
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  # OAuth2 configuration (if using OAuth2)
  # security:
  #   oauth2:
  #     resourceserver:
  #       jwt:
  #         issuer-uri: http://localhost:8081/auth/realms/nutrilife

# JWT Configuration
jwt:
  secret: nutrilife-secret-key-for-profile-service-very-long-and-secure-key-must-be-at-least-256-bits
  expiration: 86400000 # 24 hours

# Service Discovery (if needed)
# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/
#   instance:
#     prefer-ip-address: true
#     instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    com.superapp.nutrilife.profile: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
