server:
  port: 8082

spring:
  application:
    name: nutrilife-profile-service
  
  datasource:
    url: jdbc:postgresql://nutrilife-profile-db:5432/nutrilife_profile
    username: nutrilife_user
    password: nutrilife_password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://nutrilife-auth:8081/auth/realms/nutrilife

# JWT Configuration
jwt:
  secret: nutrilife-secret-key-for-profile-service-very-long-and-secure-key-must-be-at-least-256-bits
  expiration: 86400000 # 24 hours

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    com.superapp.nutrilife.profile: INFO
    org.springframework.security: WARN
    org.springframework.web: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
